### ISSUE TITLE
SbtEclipsify 0.10 has problems with Databinder Dispatch project

### ISSUE THREAD

**Issue by NYCBrit** [musk/SbtEclipsify#21]
I've got SbtEclipsify 0.10 working on the Databinder Dispatch library, but there's a few problems if you want to build it in eclipse.
- The Dispatch super-project creates an empty .project file, and the eclipse import wizard doesn't recurse past it. You have to delete the .project file in the root dir to get it to find the subproject .project files
- The Eclipse Scala plugin doesn't recognise the "scalabuilder" nature. Workaround is to remove and reapply the nature in eclipse. 
- The subprojects are imported in to eclipse with names like dispatch-core and dispatch-http, however their dependencies are on projects without the "dispatch-" prefix. Workaround is to rename all the dispatch projects in eclipse

**Comment by musk** [comment]
I'll take a look at it and will add a skip root option to skip root project
creation.

thanks for the feedback
Stefan
Am 07.08.2011 07:07 schrieb "NYCBrit" <
reply@reply.github.com>:

**Comment by musk** [comment]
Ok I added a skip-root option in order to skip the root project during generation of the project and classpath files. The scalabuilder and nature get properly applied make sure that you clean your plugin cache so that you are not running into any stale plugin data. 
The naming issue is not a bug all subproject are named dispatch-\* in the Project definition and that is the name that is used for the project name. It is not he directory name that is used. 
I pushed a new snapshot version to scala-tools with the fixes. As said befor make sure that the cache is clean before trying it out.

**Comment by NYCBrit** [comment]
Thanks for the quick response!
The skip-root works now, but I'm still getting problems with the build. 
1. Eclipse reads the .scala files as Java files until I remove & reapply the Scala nature (in eclipse). Comparing the .project file before & after, sbtEclipsify is adding a <buildCommand> for org.eclipse.jdt.core.javabuilder which shouldn't be there.
2. The dispatch-http project references dispatch-core and dispatch-futures. In the .classfile, sbtEclipsify creates path="/core" instead of path="/dispatch-core". I presume path refers to the project's path in eclipse rather than the actual folder path.

**Comment by musk** [comment]
I'll take a look at it immediatly.

**Comment by musk** [comment]
Ok issues are fixed. I'm now referencing projects by name and the javabuilder was removed from the scala nature. 
Thanks for the feedback
